export default {
	navigation: {
		bg: require('../../../assets/visual/navigation-bg.png'),
		logo: require('../../../assets/marketplace/flag.png'),
		mobileBackground: require('../../../assets/visual/mobile-navigation-bg.png'),
		userIconBackground: require('../../../assets/visual/user-icon-bg.png'),
		separator: require('../../../assets/visual/separator.png'),
		highlightVisual: require('../../../assets/visual/navi-highlight-visual.png'),
	},
	mint: {
		keyVisual: require('../../../assets/mint/key-visual.png'),
		cards: require('../../../assets/mint/cards.png'),
	},
	marketplace: {
		headingBackground: require('../../../assets/marketplace/heading-background.png'),
		mainBackground: require('../../../assets/marketplace/main-background.png'),
		underRealmButton: {
			normal: {
				left: require('../../../assets/marketplace/under-realm-normal-left-edge.png'),
				middle: require('../../../assets/marketplace/under-realm-normal-middle.png'),
				right: require('../../../assets/marketplace/under-realm-normal-right-edge.png'),
			},
			hover: {
				left: require('../../../assets/marketplace/under-realm-hover-left-edge.png'),
				middle: require('../../../assets/marketplace/under-realm-hover-middle.png'),
				right: require('../../../assets/marketplace/under-realm-hover-right-edge.png'),
			},
		},
		underRealmSubButton: {
			normal: {
				left: require('../../../assets/marketplace/under-realm-sub-normal-left-edge.png'),
				middle: require('../../../assets/marketplace/under-realm-sub-normal-middle.png'),
				right: require('../../../assets/marketplace/under-realm-sub-normal-right-edge.png'),
			},
			hover: {
				left: require('../../../assets/marketplace/under-realm-sub-hover-left-edge.png'),
				middle: require('../../../assets/marketplace/under-realm-sub-hover-middle.png'),
				right: require('../../../assets/marketplace/under-realm-sub-hover-right-edge.png'),
			},
		},
		card: {
			back: require('../../../assets/marketplace/under-realm-card-back.png'),
			front: require('../../../assets/marketplace/under-realm-card-front.png'),
		},
		mintBanner: require('../../../assets/marketplace/mint-banner.png'),
		coinUsd: require('../../../assets/marketplace/coin-usd.png'),
		mintWhyBuyNft: {
			edgeTopLeft: require('../../../assets/marketplace/mint-top-left-edge.png'),
			edgeTopRight: require('../../../assets/marketplace/mint-top-right-edge.png'),
			edgeBottomLeft: require('../../../assets/marketplace/mint-bottom-left-edge.png'),
			edgeBottomRight: require('../../../assets/marketplace/mint-bottom-right-edge.png'),
			borderTop: require('../../../assets/marketplace/mint-top-border.png'),
			borderBottom: require('../../../assets/marketplace/mint-bottom-border.png'),
			borderLeft: require('../../../assets/marketplace/mint-left-border.png'),
			borderRight: require('../../../assets/marketplace/mint-right-border.png'),
			background: require('../../../assets/marketplace/mint-bg.png'),
			bloodDrop: require('../../../assets/marketplace/icon-blood-drop.png'),
			patternTopLeft: require('../../../assets/marketplace/mint-top-left-pattern.png'),
			patternTopRight: require('../../../assets/marketplace/mint-top-right-pattern.png'),
			patternBottomLeft: require('../../../assets/marketplace/mint-bottom-left-pattern.png'),
			patternBottomRight: require('../../../assets/marketplace/mint-bottom-right-pattern.png'),
		},
		faq: {
			top: require('../../../assets/marketplace/faq-top.png'),
			middle: require('../../../assets/marketplace/faq-middle.png'),
			bottom: require('../../../assets/marketplace/faq-bottom.png'),
		},
		chevronDown: require('../../../assets/marketplace/chevron-down.png'),
		titleSeparator: require('../../../assets/marketplace/title-separator.png'),
		buyButtonBackground: require('../../../assets/marketplace/buy-button-bg.png'),
		buyButtonDash: require('../../../assets/marketplace/buy-button-inner-dash.png'),
		popupBorder: require('../../../assets/marketplace/popup-border.png'),
		popupBackground: require('../../../assets/marketplace/popup-bg.png'),
	},
	home: {
		headingBackground: require('../../../assets/home/heading-background.png'),
		cardsImage: require('../../../assets/home/cards-image.png'),
		battlefieldBackground: require('../../../assets/home/battlefield-background.png'),
		cardExplainBackground: require('../../../assets/home/card-explain-background.png'),
		cardExplain: require('../../../assets/home/card-explain.png'),
		elementalInteractionFirstBackground: require('../../../assets/home/elemental-interaction-first-background.png'),
		elementalInteractionSecondBackground: require('../../../assets/home/elemental-interaction-second-background.png'),
		elementalInteractionVisual: require('../../../assets/home/elemental-interaction-visual.png'),
		cardTypesBackground: require('../../../assets/home/card-type-background.png'),
		cardTypesHeroVisual: require('../../../assets/home/card-type-hero-visual.png'),
		cardTypesSpellVisual: require('../../../assets/home/card-type-spell-visual.png'),
		cardTypesTroopVisual: require('../../../assets/home/card-type-troop-visual.png'),
		classes: {
			background: require('../../../assets/home/classes/background.png'),
			logoBackground: require('../../../assets/home/classes/logo-background.png'),
			borderBackground: require('../../../assets/home/classes/border-background.png'),
			classContentBackground: require('../../../assets/home/classes/class-content-background.png'),
			summoner: {
				backgroundActive: require('../../../assets/home/classes/summoner/class-background-active.png'),
				logoBackgroundActive: require('../../../assets/home/classes/summoner/logo-background-active.png'),
				logo: require('../../../assets/home/classes/summoner/logo.png'),
				logoActive: require('../../../assets/home/classes/summoner/logo-active.png'),
			},
			assassin: {
				backgroundActive: require('../../../assets/home/classes/assassin/class-background-active.png'),
				logoBackgroundActive: require('../../../assets/home/classes/assassin/logo-background-active.png'),
				logo: require('../../../assets/home/classes/assassin/logo.png'),
				logoActive: require('../../../assets/home/classes/assassin/logo-active.png'),
			},
			wizard: {
				backgroundActive: require('../../../assets/home/classes/wizard/class-background-active.png'),
				logoBackgroundActive: require('../../../assets/home/classes/wizard/logo-background-active.png'),
				logo: require('../../../assets/home/classes/wizard/logo.png'),
				logoActive: require('../../../assets/home/classes/wizard/logo-active.png'),
			},
			tanker: {
				backgroundActive: require('../../../assets/home/classes/tanker/class-background-active.png'),
				logoBackgroundActive: require('../../../assets/home/classes/tanker/logo-background-active.png'),
				logo: require('../../../assets/home/classes/tanker/logo.png'),
				logoActive: require('../../../assets/home/classes/tanker/logo-active.png'),
			},
			knight: {
				backgroundActive: require('../../../assets/home/classes/knight/class-background-active.png'),
				logoBackgroundActive: require('../../../assets/home/classes/knight/logo-background-active.png'),
				logo: require('../../../assets/home/classes/knight/logo.png'),
				logoActive: require('../../../assets/home/classes/knight/logo-active.png'),
			},
		},
		socialNetworkBackground: require('../../../assets/home/social-network-background.png'),
		socialNetworkMiddleBackground: require('../../../assets/home/social-network-middle-background.png'),
	},
	guide: {
		headingBackground: require('../../../assets/guide/heading-background.png'),
		mainBackground: require('../../../assets/guide/main-background.png'),
		battlefieldIconNormal: require('../../../assets/guide/battlefield-icon-normal.png'),
		battlefieldIconActive: require('../../../assets/guide/battlefield-icon-active.png'),
		playIconNormal: require('../../../assets/guide/play-icon-normal.png'),
		playIconActive: require('../../../assets/guide/play-icon-active.png'),
		cardIconNormal: require('../../../assets/guide/card-icon-normal.png'),
		cardIconActive: require('../../../assets/guide/card-icon-active.png'),
		battleIcon: require('../../../assets/guide/battle-icon.png'),
		deckIcon: require('../../../assets/guide/deck-icon.png'),
		drawIcon: require('../../../assets/guide/draw-icon.png'),
		endTurnIcon: require('../../../assets/guide/end-turn-icon.png'),
		graveIcon: require('../../../assets/guide/grave-icon.png'),
		handIcon: require('../../../assets/guide/hand-icon.png'),
		healthPointIcon: require('../../../assets/guide/health-point-icon.png'),
		heroIcon: require('../../../assets/guide/hero-icon.png'),
		historyIcon: require('../../../assets/guide/history-icon.png'),
		setupIcon: require('../../../assets/guide/setup-icon.png'),
		spellIcon: require('../../../assets/guide/spell-icon.png'),
		summonZoneIcon: require('../../../assets/guide/summon-zone-icon.png'),
		troopIcon: require('../../../assets/guide/troop-icon.png'),
		battlefieldImage: require('../../../assets/guide/battlefield-image.png'),
		cardExplain: require('../../../assets/guide/card-explain.png'),
		elementalInteractionVisual: require('../../../assets/guide/elemental-interaction-visual.png'),
		footerMainBackground: require('../../../assets/guide/footer-main-background.png'),
		footerContentBackground: require('../../../assets/guide/footer-content-background.png'),
		effectOverlay: require('../../../assets/guide/effect-overlay.png'),
		handImage: require('../../../assets/guide/hand-image.png'),
		deckImage: require('../../../assets/guide/deck-image.png'),
		magicTowerImage: require('../../../assets/guide/magic-tower-image.png'),
		summonImage: require('../../../assets/guide/summon-image.png'),
		endTurnImage: require('../../../assets/guide/end-turn-image.png'),
		healthPointImage: require('../../../assets/guide/health-point-image.png'),
	},
	lobby: {
		lobbyBackground: require('../../../assets/lobby/lobby-background.png'),
		playBannerBackground: require('../../../assets/lobby/play-banner-background.png'),
		buildBannerBackground: require('../../../assets/lobby/build-banner-background.png'),
	},
	story: {
		headerBackground: require('../../../assets/story/header-background.png'),
		headerFlag: require('../../../assets/story/header-flag.png'),
		mainBackground: require('../../../assets/story/main-background.png'),
		atemWorldMap: require('../../../assets/story/atem-world-map.png'),
		knightIconNormal: require('../../../assets/story/knight-icon-normal.png'),
		knightIconActive: require('../../../assets/story/knight-icon-active.png'),
		tankIconNormal: require('../../../assets/story/tank-icon-normal.png'),
		tankIconActive: require('../../../assets/story/tank-icon-active.png'),
		summonerIconNormal: require('../../../assets/story/summoner-icon-normal.png'),
		summonerIconActive: require('../../../assets/story/summoner-icon-active.png'),
		wizardIconNormal: require('../../../assets/story/wizard-icon-normal.png'),
		wizardIconActive: require('../../../assets/story/wizard-icon-active.png'),
		assasinIconNormal: require('../../../assets/story/assasin-icon-normal.png'),
		assasinIconActive: require('../../../assets/story/assasin-icon-active.png'),
		knightImage: require('../../../assets/story/knight-image.png'),
		tankImage: require('../../../assets/story/tank-image.png'),
		summonerImage: require('../../../assets/story/summoner-image.png'),
		wizardImage: require('../../../assets/story/wizard-image.png'),
		assasinImage: require('../../../assets/story/assassin-image.png'),
		ellipse: require('../../../assets/story/ellipse.png'),
		externalWarNormal: require('../../../assets/story/external-war-normal.png'),
		externalWarActive: require('../../../assets/story/external-war-active.png'),
		externalWarPassive: require('../../../assets/story/external-war-passive.png'),
		labelShape: require('../../../assets/story/label-shape.png'),
		chevron: require('../../../assets/story/chevron.png'),
	},
	cardLibrary: {
		mainBackground: require('../../../assets/cardLibrary/main-background.png'),
		cardsImage: require('../../../assets/cardLibrary/cards-image.png'),
		arrow: require('../../../assets/cardLibrary/arrow.png'),
		dropdownSide: require('../../../assets/cardLibrary/dropdown-side.png'),
		searchBackground: require('../../../assets/cardLibrary/search-background.png'),
		searchIcon: require('../../../assets/cardLibrary/search-icon.png'),
		normalFilterIcon: require('../../../assets/cardLibrary/normal-filter-icon.png'),
		activeFilterIcon: require('../../../assets/cardLibrary/active-filter-icon.png'),
		expandedSearchBarBackground: require('../../../assets/cardLibrary/expanded-search-bar-background.png'),
		effectSelectType: require('../../../assets/cardLibrary/effect-select-type.png'),
		normalFilterButton: require('../../../assets/cardLibrary/normal-filter-button.png'),
		activeFilterButton: require('../../../assets/cardLibrary/active-filter-button.png'),
		clearIcon: require('../../../assets/cardLibrary/clear-icon.png'),
		dropdownButtonNormal: require('../../../assets/cardLibrary/dropdown-button-normal.png'),
		dropdownButtonActive: require('../../../assets/cardLibrary/dropdown-button-active.png'),
		detailTankerIcon: require('../../../assets/cardLibrary/detail-tanker-icon.png'),
		detailAssassinIcon: require('../../../assets/cardLibrary/detail-assassin-icon.png'),
		detailKnightIcon: require('../../../assets/cardLibrary/detail-knight-icon.png'),
		detailSummonerIcon: require('../../../assets/cardLibrary/detail-summoner-icon.png'),
		detailWizardIcon: require('../../../assets/cardLibrary/detail-wizard-icon.png'),
		fireIcon: require('../../../assets/cardLibrary/fire-icon.png'),
		darkIcon: require('../../../assets/cardLibrary/dark-icon.png'),
		earthIcon: require('../../../assets/cardLibrary/earth-icon.png'),
		lightIcon: require('../../../assets/cardLibrary/light-icon.png'),
		metalIcon: require('../../../assets/cardLibrary/metal-icon.png'),
		waterIcon: require('../../../assets/cardLibrary/water-icon.png'),
		woodIcon: require('../../../assets/cardLibrary/wood-icon.png'),
		attackIcon: require('../../../assets/cardLibrary/attack-icon.png'),
		defenseIcon: require('../../../assets/cardLibrary/defense-icon.png'),
		hpIcon: require('../../../assets/cardLibrary/hp-icon.png'),
		rightArrow: require('../../../assets/cardLibrary/right-arrow.png'),
	},
	card: {
		back: require('../../../assets/card/back.png'),
		front: require('../../../assets/card/front.png'),
		gem: require('../../../assets/card/gem.png'),
		class: {
			assassin: require('../../../assets/card/class-assassin.png'),
			knight: require('../../../assets/card/class-knight.png'),
			summoner: require('../../../assets/card/class-summoner.png'),
			tanker: require('../../../assets/card/class-tank.png'),
			wizard: require('../../../assets/card/class-wizard.png'),
		},
		foil: {
			dark: require('../../../assets/card/foil-dark.png'),
			earth: require('../../../assets/card/foil-earth.png'),
			fire: require('../../../assets/card/foil-fire.png'),
			light: require('../../../assets/card/foil-light.png'),
			metal: require('../../../assets/card/foil-metal.png'),
			water: require('../../../assets/card/foil-water.png'),
			wood: require('../../../assets/card/foil-wood.png'),
		},
		type: {
			all: require('../../../assets/card/type-all.png'),
			hero: require('../../../assets/card/type-hero.png'),
			spell: require('../../../assets/card/type-spell.png'),
			troop: require('../../../assets/card/type-troop.png'),
		},
	},
};
