export default {
	navigation: {
		bg: { uri: '/visual/navigation-bg.png' },
		logo: { uri: '/marketplace/flag.png' },
		mobileBackground: { uri: '/visual/mobile-navigation-bg.png' },
		userIconBackground: { uri: '/visual/user-icon-bg.png' },
		separator: { uri: '/visual/separator.png' },
		highlightVisual: { uri: '/visual/navi-highlight-visual.png' },
	},
	mint: {
		keyVisual: { uri: '/mint/key-visual.png' },
		cards: { uri: '/mint/cards.png' },
	},
	marketplace: {
		headingBackground: { uri: '/marketplace/heading-background.png' },
		mainBackground: { uri: '/marketplace/main-background.png' },
		underRealmButton: {
			normal: {
				left: { uri: '/marketplace/under-realm-normal-left-edge.png' },
				middle: { uri: '/marketplace/under-realm-normal-middle.png' },
				right: { uri: '/marketplace/under-realm-normal-right-edge.png' },
			},
			hover: {
				left: { uri: '/marketplace/under-realm-hover-left-edge.png' },
				middle: { uri: '/marketplace/under-realm-hover-middle.png' },
				right: { uri: '/marketplace/under-realm-hover-right-edge.png' },
			},
		},
		underRealmSubButton: {
			normal: {
				left: { uri: '/marketplace/under-realm-sub-normal-left-edge.png' },
				middle: { uri: '/marketplace/under-realm-sub-normal-middle.png' },
				right: { uri: '/marketplace/under-realm-sub-normal-right-edge.png' },
			},
			hover: {
				left: { uri: '/marketplace/under-realm-sub-hover-left-edge.png' },
				middle: { uri: '/marketplace/under-realm-sub-hover-middle.png' },
				right: { uri: '/marketplace/under-realm-sub-hover-right-edge.png' },
			},
		},
		card: {
			back: { uri: '/marketplace/under-realm-card-back.png' },
			front: { uri: '/marketplace/under-realm-card-front.png' },
		},
		mintBanner: { uri: '/marketplace/mint-banner.png' },
		coinUsd: { uri: '/marketplace/coin-usd.png' },
		mintWhyBuyNft: {
			edgeTopLeft: { uri: '/marketplace/mint-top-left-edge.png' },
			edgeTopRight: { uri: '/marketplace/mint-top-right-edge.png' },
			edgeBottomLeft: { uri: '/marketplace/mint-bottom-left-edge.png' },
			edgeBottomRight: { uri: '/marketplace/mint-bottom-right-edge.png' },
			borderTop: { uri: '/marketplace/mint-top-border.png' },
			borderBottom: { uri: '/marketplace/mint-bottom-border.png' },
			borderLeft: { uri: '/marketplace/mint-left-border.png' },
			borderRight: { uri: '/marketplace/mint-right-border.png' },
			background: { uri: '/marketplace/mint-bg.png' },
			bloodDrop: { uri: '/marketplace/icon-blood-drop.png' },
			patternTopLeft: { uri: '/marketplace/mint-top-left-pattern.png' },
			patternTopRight: { uri: '/marketplace/mint-top-right-pattern.png' },
			patternBottomLeft: { uri: '/marketplace/mint-bottom-left-pattern.png' },
			patternBottomRight: { uri: '/marketplace/mint-bottom-right-pattern.png' },
		},
		faq: {
			top: { uri: '/marketplace/faq-top.png' },
			middle: { uri: '/marketplace/faq-middle.png' },
			bottom: { uri: '/marketplace/faq-bottom.png' },
		},
		chevronDown: { uri: '/marketplace/chevron-down.png' },
		titleSeparator: { uri: '/marketplace/title-separator.png' },
		buyButtonBackground: { uri: '/marketplace/buy-button-bg.png' },
		buyButtonDash: { uri: '/marketplace/buy-button-inner-dash.png' },
		popupBorder: { uri: '/marketplace/popup-border.png' },
		popupBackground: { uri: '/marketplace/popup-bg.png' },
	},
	home: {
		headingBackground: { uri: '/home/heading-background.png' },
		cardsImage: { uri: '/home/cards-image.png' },
		battlefieldBackground: { uri: '/home/battlefield-background.png' },
		cardExplainBackground: { uri: '/home/card-explain-background.png' },
		cardExplain: { uri: '/home/card-explain.png' },
		elementalInteractionFirstBackground: {
			uri: '/home/elemental-interaction-first-background.png',
		},
		elementalInteractionSecondBackground: {
			uri: '/home/elemental-interaction-second-background.png',
		},
		elementalInteractionVisual: {
			uri: '/home/elemental-interaction-visual.png',
		},
		cardTypesBackground: { uri: '/home/card-type-background.png' },
		cardTypesHeroVisual: { uri: '/home/card-type-hero-visual.png' },
		cardTypesSpellVisual: { uri: '/home/card-type-spell-visual.png' },
		cardTypesTroopVisual: { uri: '/home/card-type-troop-visual.png' },
		classes: {
			background: { uri: '/home/classes/background.png' },
			logoBackground: { uri: '/home/classes/logo-background.png' },
			borderBackground: { uri: '/home/classes/border-background.png' },
			classContentBackground: {
				uri: '/home/classes/class-content-background.png',
			},
			summoner: {
				backgroundActive: {
					uri: '/home/classes/summoner/class-background-active.png',
				},
				logoBackgroundActive: {
					uri: '/home/classes/summoner/logo-background-active.png',
				},
				logo: { uri: '/home/classes/summoner/logo.png' },
				logoActive: { uri: '/home/classes/summoner/logo-active.png' },
			},
			assassin: {
				backgroundActive: {
					uri: '/home/classes/assassin/class-background-active.png',
				},
				logoBackgroundActive: {
					uri: '/home/classes/assassin/logo-background-active.png',
				},
				logo: { uri: '/home/classes/assassin/logo.png' },
				logoActive: { uri: '/home/classes/assassin/logo-active.png' },
			},
			wizard: {
				backgroundActive: {
					uri: '/home/classes/wizard/class-background-active.png',
				},
				logoBackgroundActive: {
					uri: '/home/classes/wizard/logo-background-active.png',
				},
				logo: { uri: '/home/classes/wizard/logo.png' },
				logoActive: { uri: '/home/classes/wizard/logo-active.png' },
			},
			tanker: {
				backgroundActive: {
					uri: '/home/classes/tanker/class-background-active.png',
				},
				logoBackgroundActive: {
					uri: '/home/classes/tanker/logo-background-active.png',
				},
				logo: { uri: '/home/classes/tanker/logo.png' },
				logoActive: { uri: '/home/classes/tanker/logo-active.png' },
			},
			knight: {
				backgroundActive: {
					uri: '/home/classes/knight/class-background-active.png',
				},
				logoBackgroundActive: {
					uri: '/home/classes/knight/logo-background-active.png',
				},
				logo: { uri: '/home/classes/knight/logo.png' },
				logoActive: { uri: '/home/classes/knight/logo-active.png' },
			},
		},
		socialNetworkBackground: { uri: '/home/social-network-background.png' },
		socialNetworkMiddleBackground: {
			uri: '/home/social-network-middle-background.png',
		},
	},
	guide: {
		headingBackground: { uri: '/guide/heading-background.png' },
		mainBackground: { uri: '/guide/main-background.png' },
		battlefieldIconNormal: { uri: '/guide/battlefield-icon-normal.png' },
		battlefieldIconActive: { uri: '/guide/battlefield-icon-active.png' },
		playIconNormal: { uri: '/guide/play-icon-normal.png' },
		playIconActive: { uri: '/guide/play-icon-active.png' },
		cardIconNormal: { uri: '/guide/card-icon-normal.png' },
		cardIconActive: { uri: '/guide/card-icon-active.png' },
		battleIcon: { uri: '/guide/battle-icon.png' },
		deckIcon: { uri: '/guide/deck-icon.png' },
		drawIcon: { uri: '/guide/draw-icon.png' },
		endTurnIcon: { uri: '/guide/end-turn-icon.png' },
		graveIcon: { uri: '/guide/grave-icon.png' },
		handIcon: { uri: '/guide/hand-icon.png' },
		healthPointIcon: { uri: '/guide/health-point-icon.png' },
		heroIcon: { uri: '/guide/hero-icon.png' },
		historyIcon: { uri: '/guide/history-icon.png' },
		setupIcon: { uri: '/guide/setup-icon.png' },
		spellIcon: { uri: '/guide/spell-icon.png' },
		summonZoneIcon: { uri: '/guide/summon-zone-icon.png' },
		troopIcon: { uri: '/guide/troop-icon.png' },
		battlefieldImage: { uri: '/guide/battlefield-image.png' },
		cardExplain: { uri: '/guide/card-explain.png' },
		elementalInteractionVisual: {
			uri: '/guide/elemental-interaction-visual.png',
		},
		footerMainBackground: { uri: '/guide/footer-main-background.png' },
		footerContentBackground: { uri: '/guide/footer-content-background.png' },
		effectOverlay: { uri: '/guide/effect-overlay.png' },
		handImage: { uri: '/guide/hand-image.png' },
		deckImage: { uri: '/guide/deck-image.png' },
		magicTowerImage: { uri: '/guide/magic-tower-image.png' },
		summonImage: { uri: '/guide/summon-image.png' },
		endTurnImage: { uri: '/guide/end-turn-image.png' },
		healthPointImage: { uri: '/guide/health-point-image.png' },
	},
	lobby: {
		lobbyBackground: { uri: '/lobby/lobby-background.png' },
		playBannerBackground: { uri: '/lobby/play-banner-background.png' },
		buildBannerBackground: { uri: '/lobby/build-banner-background.png' },
	},
	story: {
		headerBackground: { uri: '/story/header-background.png' },
		headerFlag: { uri: '/story/header-flag.png' },
		mainBackground: { uri: '/story/main-background.png' },
		atemWorldMap: { uri: '/story/atem-world-map.png' },
		knightIconNormal: { uri: '/story/knight-icon-normal.png' },
		knightIconActive: { uri: '/story/knight-icon-active.png' },
		tankIconNormal: { uri: '/story/tank-icon-normal.png' },
		tankIconActive: { uri: '/story/tank-icon-active.png' },
		summonerIconNormal: { uri: '/story/summoner-icon-normal.png' },
		summonerIconActive: { uri: '/story/summoner-icon-active.png' },
		wizardIconNormal: { uri: '/story/wizard-icon-normal.png' },
		wizardIconActive: { uri: '/story/wizard-icon-active.png' },
		assasinIconNormal: { uri: '/story/assasin-icon-normal.png' },
		assasinIconActive: { uri: '/story/assasin-icon-active.png' },
		knightImage: { uri: '/story/knight-image.png' },
		tankImage: { uri: '/story/tank-image.png' },
		summonerImage: { uri: '/story/summoner-image.png' },
		wizardImage: { uri: '/story/wizard-image.png' },
		assasinImage: { uri: '/story/assassin-image.png' },
		ellipse: { uri: '/story/ellipse.png' },
		externalWarNormal: { uri: '/story/external-war-normal.png' },
		externalWarActive: { uri: '/story/external-war-active.png' },
		externalWarPassive: { uri: '/story/external-war-passive.png' },
		labelShape: { uri: '/story/label-shape.png' },
		chevron: { uri: '/story/chevron.png' },
	},
	cardLibrary: {
		mainBackground: { uri: 'cardLibrary/main-background.png' },
		cardsImage: { uri: 'cardLibrary/cards-image.png' },
		arrow: { uri: '/cardLibrary/arrow.png' },
		dropdownSide: { uri: '/cardLibrary/dropdown-side.png' },
		searchBackground: { uri: '/cardLibrary/search-background.png' },
		searchIcon: { uri: '/cardLibrary/search-icon.png' },
		normalFilterIcon: { uri: '/cardLibrary/normal-filter-icon.png' },
		activeFilterIcon: { uri: '/cardLibrary/active-filter-icon.png' },
		expandedSearchBarBackground: {
			uri: '/cardLibrary/expanded-search-bar-background.png',
		},
		effectSelectType: { uri: '/cardLibrary/effect-select-type.png' },
		normalFilterButton: { uri: '/cardLibrary/normal-filter-button.png' },
		activeFilterButton: { uri: '/cardLibrary/active-filter-button.png' },
		clearIcon: { uri: '/cardLibrary/clear-icon.png' },
		dropdownButtonNormal: { uri: '/cardLibrary/dropdown-button-normal.png' },
		dropdownButtonActive: { uri: '/cardLibrary/dropdown-button-active.png' },
		detailTankerIcon: { uri: '/cardLibrary/detail-tanker-icon.png' },
		detailAssassinIcon: { uri: '/cardLibrary/detail-assassin-icon.png' },
		detailKnightIcon: { uri: '/cardLibrary/detail-knight-icon.png' },
		detailSummonerIcon: { uri: '/cardLibrary/detail-summoner-icon.png' },
		detailWizardIcon: { uri: '/cardLibrary/detail-wizard-icon.png' },
		fireIcon: { uri: '/cardLibrary/fire-icon.png' },
		darkIcon: { uri: '/cardLibrary/dark-icon.png' },
		earthIcon: { uri: '/cardLibrary/earth-icon.png' },
		lightIcon: { uri: '/cardLibrary/light-icon.png' },
		metalIcon: { uri: '/cardLibrary/metal-icon.png' },
		waterIcon: { uri: '/cardLibrary/water-icon.png' },
		woodIcon: { uri: '/cardLibrary/wood-icon.png' },
		attackIcon: { uri: '/cardLibrary/attack-icon.png' },
		defenseIcon: { uri: '/cardLibrary/defense-icon.png' },
		hpIcon: { uri: '/cardLibrary/hp-icon.png' },
		rightArrow: { uri: '/cardLibrary/right-arrow.png' },
	},
	card: {
		back: { uri: '/card/back.png' },
		front: { uri: '/card/front.png' },
		gem: { uri: '/card/gem.png' },
		class: {
			assassin: { uri: '/card/class-assassin.png' },
			knight: { uri: '/card/class-knight.png' },
			summoner: { uri: '/card/class-summoner.png' },
			tanker: { uri: '/card/class-tank.png' },
			wizard: { uri: '/card/class-wizard.png' },
		},
		foil: {
			dark: { uri: '/card/foil-dark.png' },
			earth: { uri: '/card/foil-earth.png' },
			fire: { uri: '/card/foil-fire.png' },
			light: { uri: '/card/foil-light.png' },
			metal: { uri: '/card/foil-metal.png' },
			water: { uri: '/card/foil-water.png' },
			wood: { uri: '/card/foil-wood.png' },
		},
		type: {
			all: { uri: '/card/type-all.png' },
			hero: { uri: '/card/type-hero.png' },
			spell: { uri: '/card/type-spell.png' },
			troop: { uri: '/card/type-troop.png' },
		},
	},
};
